import ProjectDescription

let workspace = Workspace(
  name: "SilentCameraWorkSpace",
  projects: [
    "App/**",
    "Domain/**",
    "Presentation/**",
    "Utility/**",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)
